Remove check for previous configuration.env

diff --git a/.github/workflows/image.build.yml b/.github/workflows/image.build.yml
--- a/.github/workflows/image.build.yml
+++ b/.github/workflows/image.build.yml
@@ -100,20 +100,15 @@ jobs:
         id: configuration_directory
         run: echo "::set-output name=value::./services/${{ matrix.service_id }}"
 
-      - name: Set service configuration path
-        id: configuration_path
-        run: |
-          FILE_PATH="${{ steps.configuration_directory.outputs.value }}/configuration.env"
-          if [ ! -f "$FILE_PATH" ]; then
-            echo "Configuration for service ${{ matrix.service_id }} not found: $FILE_PATH"
-            exit 1
-          fi
-
-          echo "::set-output name=value::$FILE_PATH"
-
       - name: Read service version
         id: version
         run: |
+          FILE_PATH="${{ steps.configuration_directory.outputs.value }}/version"
+          if [ ! -f "$FILE_PATH" ]; then
+            echo "Version for service ${{ matrix.service_id }} not found: $FILE_PATH"
+            exit 1
+          fi
+
           (echo "::set-output name=value::$(cat)") < ${{ steps.configuration_path.outputs.value }}
 
       - name: Set path to image definition
