Remove check-service-configuration-exists.sh (#494)

diff --git a/.github/workflows/image.build.yml b/.github/workflows/image.build.yml
--- a/.github/workflows/image.build.yml
+++ b/.github/workflows/image.build.yml
@@ -62,10 +62,13 @@ jobs:
         uses: actions/checkout@v2
 
       - name: Verify service configuration exists
+        env:
+          FILE_PATH: ${{ steps.configuration_path.outputs.value }}
         run: |
-          ./ci/scripts/check-service-configuration-exists.sh \
-          "${{ github.event.inputs.service_id }}" \
-          "${{ steps.configuration_path.outputs.value }}"
+          if [ ! -f "$FILE_PATH" ]; then
+            echo "Configuration for service ${{ github.event.inputs.service_id }} not found: $FILE_PATH"
+            exit 1
+          fi
 
       - name: Set path to image definition
         id: image_definition_path
